/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC"
 * 	found in "description.asn1"
 * 	`asn1c -D src -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RRCSetupComplete_H_
#define	_RRCSetupComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCSetupComplete-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCSetupComplete */
typedef struct RRCSetupComplete {
	RRCSetupComplete_IEs_t	 rrcSetupComplete;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetupComplete_H_ */
#include <asn_internal.h>
