/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC"
 * 	found in "description.asn1"
 * 	`asn1c -D src -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RRCSetupComplete_IEs_H_
#define	_RRCSetupComplete_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitialUE-Identity.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCSetupComplete-IEs */
typedef struct RRCSetupComplete_IEs {
	InitialUE_Identity_t	 ue_Identity;
	BIT_STRING_t	 spare;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCSetupComplete_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCSetupComplete_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetupComplete_IEs_H_ */
#include <asn_internal.h>
